version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google-auth
    versions:
    - 1.25.0
    - 1.26.0
    - 1.26.1
    - 1.28.1
    - 1.29.0
    - 1.30.0
  - dependency-name: google-api-python-client
    versions:
    - 2.2.0
  - dependency-name: google-cloud-storage
    versions:
    - 1.35.1
    - 1.36.1
    - 1.37.1
  - dependency-name: protobuf
    versions:
    - 3.15.0
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.6
    - 3.15.7
  - dependency-name: google-api-core
    versions:
    - 1.26.1
    - 1.26.2
